version: '3'

services: 

  app:
    build:
      dockerfile: .docker/app/Dockerfile
      context: .
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s /entrypoint.sh
    tty: true
    volumes: 
      - ./www/app:/usr/src/app
    networks: 
      - node-network
    depends_on: 
      - db
  
  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www
    networks:
      - node-network
    depends_on:
      - app

  db:
    build: ./.docker/mysql
    container_name: mysql
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge